version: "3.7"

services:
  database_alugueis:
    image: postgres
    container_name: database_alugueis
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=alugueis
    volumes:
      - .:/data/postgres
  app:
    build: .
    container_name: alugueis_backend
    restart: always
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database_alugueis
    depends_on:
      - database_alugueis
